### PR TITLE
WIP: Limit action space during training

### LINKED ISSUE #26: Enable limitation of the action space based on the set of "positive" actions
Copied from hpi-www-midl-text-localization/text-localization-agent#1

### PR DESCRIPTION
**Pull request by bakoe**
Closes #26 
Contributes to hpi-www-midl-text-localization/text-localization-agent#1

### CODE REVIEW

**Review by J-L-O — CHANGES_REQUESTED** [review]
Looks good in general, but this line in the `step` method
https://github.com/hpi-www-midl-text-localization/text-localization-environment/blob/c7969caf5564358e7a146ef2686b73b163763822/text_localization_environment/TextLocEnv.py#L69
currently blocks training because the assertion might fail if the agent acts greedy, since the greedy part doesn't know of the restriction. Possible solutions are removing the assertion, changing the `contains` function or somehow making the greedy part of the agent aware of the limited action space.


I also ran some training using these commits, but it is hard to judge whether they improved learning or not, more investigation would be required to determine that. They also didn't seem to harm though, so once you fixed the issue mentioned above, I would say we can merge this.

**Comment by bakoe** [comment]
@J-L-O Thanks for noticing! You're absolutely right. I've removed the assertion. But you're right, we probably should investigate further whether the limitation of the action space actually works as expected and whether it positively influences the training performance.

**Review by J-L-O — APPROVED** [review]

**Comment by bakoe** [comment]
(marked the PR as WIP since we're it's not clear whether the change actually increases the ML performance)

**Comment by J-L-O** [comment]
We should probably delete this branch. What do you think @bakoe ?

**Pull request closed without merging**
